spring.application.name=SQL32
spring.Liquibase.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/BD31
spring.datasource.password=1f2o3x
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.postgresql.Driver

